/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sportsphere2;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;



/**
 *
 * @author HP
 */
public class AddTicket extends javax.swing.JFrame {

    /**
     * Creates new form AddTicket
     */
    public AddTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        gameid = new javax.swing.JTextField();
        seat = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        date = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 350));
        setPreferredSize(new java.awt.Dimension(500, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Game ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setText("Seat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 100, 30));

        gameid.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(gameid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 150, -1));

        seat.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, -1));

        price.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, -1));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        date.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, -1));

        jLabel1.setText("Date");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\Project\\bbbb.jpg")); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(500, 350));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
         this.setVisible(false);
        Adminmain p1 = new Adminmain();
        p1.setVisible(true);
        
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Main conn = new Main();
        
             
        String t1 = gameid.getText();
        String t2 = seat.getText();
        String t3 = price.getText();
        String t4 = date.getText();
       
        
        
        if(t1.equals("") || t1.matches("@#$%^&*()_+!")){
        
            gameid.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid Ground name");
        } 
        
        if(t2.equals("") || t2.matches("@#$%^&*()_+!")){
        
            seat.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid Ground type");
        } 
        
        if(t3.equals("") || t3.matches("@#$%^&*()_+!")){
        
            price.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid Ground ID");
        }
        
        if(t4.equals("") || t4.matches("@#$%^&*()_+!")){
        
             date.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid Ground type");
        } 
        
        
        else {
            
            try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c1=DriverManager.getConnection(conn.url, conn.user, conn.pss);
        
            String mysql = "INSERT INTO Tickets(game_id,price,seat,Date) VALUES(?,?,?,?)";
            PreparedStatement st = c1.prepareStatement(mysql);
            
            st.setString(1, t1);
            st.setString(2, t2);
            st.setString(3, t3);
            st.setString(4, t4);
            
            st.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "You add the ticket successfully");
            
                      
        }
        
        catch(Exception e){
            
    
           System.out.println(e);
           
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField date;
    private javax.swing.JTextField gameid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField price;
    private javax.swing.JTextField seat;
    // End of variables declaration//GEN-END:variables
}
