/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sportsphere2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Openpage extends javax.swing.JFrame {

    /**
     * Creates new form Openpage
     */
    
    static String name;
    static int id;
    public Openpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        pword = new javax.swing.JPasswordField();
        log = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        reg1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 80, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        uname.setBackground(new java.awt.Color(204, 255, 255));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 220, 30));

        pword.setBackground(new java.awt.Color(204, 255, 255));
        pword.setColumns(10);
        pword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwordActionPerformed(evt);
            }
        });
        getContentPane().add(pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 220, 30));

        log.setBackground(new java.awt.Color(0, 51, 255));
        log.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        log.setForeground(new java.awt.Color(255, 255, 255));
        log.setText("Login...");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        getContentPane().add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 320, 40));

        jLabel4.setBackground(new java.awt.Color(0, 153, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Don't have an exciting account");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 240, 40));

        reg1.setBackground(new java.awt.Color(0, 51, 255));
        reg1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reg1.setForeground(new java.awt.Color(255, 255, 255));
        reg1.setText("Register Now");
        reg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg1ActionPerformed(evt);
            }
        });
        getContentPane().add(reg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 180, 40));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 70)); // NOI18N
        jLabel5.setText("SPORTSPHERE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 580, 120));

        comb.setBackground(new java.awt.Color(204, 255, 255));
        comb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        getContentPane().add(comb, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 220, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\Project\\1.jpg")); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 700, -1, -1));

        jLabel7.setBackground(new java.awt.Color(204, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\Project\\aaaaaa.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        Registerpage p1 = new Registerpage();
        p1.setVisible(true);
    }//GEN-LAST:event_reg1ActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
        
        Main conn = new Main();
        
        String mail = uname.getText();
        String pass = pword.getText();
        
        if(mail.equals("") || mail.matches("#$%^&*()_+!") && !mail.equals("@")){
        
            uname.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid email");
        }
        
       if(pass.equals("")){
        
            pword.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a Password");
        }
        
        
        try{
        
            String sql="";
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c1=DriverManager.getConnection(conn.url, conn.user, conn.pss);
            
                    
       // String username = uname.getText();
       // String password = pword.getText();
        
     /*   if(uname.getText().equals("")){
        
        JOptionPane.showMessageDialog(null, "Please fill out username");
        
        }
        
        else if(pword.getText().equals("")){
         
            JOptionPane.showMessageDialog(null, "Please fill out password");
            
        }*/
            
            
            String role = comb.getSelectedItem().toString();
            if(role=="User"){
               sql = "SELECT User_ID,First_name FROM User WHERE Email = ? AND Password = ? AND Position = ?";
            }else if(role=="Admin"){
               sql = "SELECT Admin_ID,Email FROM Admin WHERE Email = ? AND Password = ? AND Position = ?";
}
               
            PreparedStatement st = c1.prepareStatement(sql);
            
            st.setString(1, uname.getText().trim());
            st.setString(2, pword.getText().trim());
            st.setString(3, comb.getSelectedItem().toString());
            ResultSet resultSet = st.executeQuery();
            
            if (resultSet.next()){
               
              
            
              id=resultSet.getInt(1);
           name=resultSet.getString(2);
                System.out.println(name);
                
                if(role=="User"){
                Mainpage p1 =new Mainpage();
                this.setVisible(false);
                p1.setVisible(true);
                JOptionPane.showMessageDialog(null, "Successfully loged in ");
            }
               
               else if(role=="Admin"){
                Adminmain p2=new Adminmain();
                this.setVisible(false);
                p2.setVisible(true);
                JOptionPane.showMessageDialog(null, "Successfully loged in");
            }
                
                
                     
            }else{
            
            JOptionPane.showMessageDialog(null, "Username or password incorrect ");
                
            }
            
        
        }
        catch(Exception e){
            
            System.out.println(e);
        
        }
        

   //     else {
        
    //        JOptionPane.showMessageDialog(null, "Wrong username or Password","Message",JOptionPane.ERROR_MESSAGE);
        
  //      }
        
        
        
        
        
        

       
        
        
    }//GEN-LAST:event_logActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void pwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Openpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Openpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Openpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Openpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Openpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton log;
    private javax.swing.JPasswordField pword;
    private javax.swing.JButton reg1;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
