/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sportsphere2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class RegGround extends javax.swing.JFrame {

    /**
     * Creates new form RegGround
     */
    public RegGround() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gname = new javax.swing.JTextField();
        gtype = new javax.swing.JTextField();
        gloc = new javax.swing.JTextField();
        gprice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        greg = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        gcapacity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ground Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ground type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Location");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Booking price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        gname.setBackground(new java.awt.Color(204, 255, 255));
        gname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnameActionPerformed(evt);
            }
        });
        getContentPane().add(gname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 280, 30));

        gtype.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(gtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 280, 30));

        gloc.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(gloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 280, 30));

        gprice.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(gprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 280, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel5.setText("Ground Registration");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        greg.setBackground(new java.awt.Color(0, 102, 255));
        greg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        greg.setForeground(new java.awt.Color(255, 255, 255));
        greg.setText("Register..");
        greg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gregActionPerformed(evt);
            }
        });
        getContentPane().add(greg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 440, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Capacity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        gcapacity.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(gcapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 280, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\Project\\aaaaaa.jpg")); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnameActionPerformed
        // TODO add your handling code here:
   
        
        
        
    }//GEN-LAST:event_gnameActionPerformed

    private void gregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gregActionPerformed
        // TODO add your handling code here:
        
        Main conn = new Main();
        
             
        String groundname = gname.getText();
        String groundtype = gtype.getText();
        String location = gloc.getText();
        String bookingprice = gprice.getText();
        String capacity = gcapacity.getText();
        
        
        if(groundname.equals("") || groundname.matches("@#$%^&*()_+!")){
        
            gname.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid Ground name");
        } 
        
        if(groundtype.equals("") || groundtype.matches("@#$%^&*()_+!")){
        
            gtype.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid Ground type");
        } 
        
        if(location.equals("") || location.matches("@#$%^&*()_+!")){
        
            gloc.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid Ground ID");
        }
        
        if(bookingprice.equals("") || bookingprice.matches("@#$%^&*()_+!")){
        
            gprice.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid Ground type");
        } 
        
        if(capacity.equals("") || capacity.matches("@#$%^&*()_+!")){
        
            gcapacity.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid Ground Capacity");
        }
        
        else {
            
            try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c1=DriverManager.getConnection(conn.url, conn.user, conn.pss);
        
            String mysql = "INSERT INTO Grounds(name,location,booking_price,type,capacity) VALUES(?,?,?,?,?)";
            PreparedStatement st = c1.prepareStatement(mysql);
            
            st.setString(1, groundname);
            st.setString(2, location);
            st.setString(3, bookingprice);
            st.setString(4, groundtype);
            st.setString(5, capacity);
            
            st.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "You Registered the Ground Succesfully ");
            
                      
        }
        
        catch(Exception e){
            
    
           System.out.println(e);
           
        }
      
    }//GEN-LAST:event_gregActionPerformed

    }
    /**
 //    * @param args the command line arguments
   // */

    /**
     * //    * @param args the command line arguments
   //
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegGround.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegGround.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegGround.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegGround.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegGround().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gcapacity;
    private javax.swing.JTextField gloc;
    private javax.swing.JTextField gname;
    private javax.swing.JTextField gprice;
    private javax.swing.JButton greg;
    private javax.swing.JTextField gtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
