/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sportsphere2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Registerpage extends javax.swing.JFrame {

    /**
     * Creates new form Registerpage
     */
    public Registerpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        addr = new javax.swing.JTextField();
        phn = new javax.swing.JTextField();
        pword1 = new javax.swing.JPasswordField();
        pword2 = new javax.swing.JPasswordField();
        reg2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("REGISTER PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 410, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Phone Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Create Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Confirm Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        fname.setBackground(new java.awt.Color(204, 255, 255));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 210, -1));

        lname.setBackground(new java.awt.Color(204, 255, 255));
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 210, -1));

        mail.setBackground(new java.awt.Color(204, 255, 255));
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 210, -1));

        addr.setBackground(new java.awt.Color(204, 255, 255));
        addr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrActionPerformed(evt);
            }
        });
        getContentPane().add(addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 210, -1));

        phn.setBackground(new java.awt.Color(204, 255, 255));
        phn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnActionPerformed(evt);
            }
        });
        getContentPane().add(phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 210, -1));

        pword1.setBackground(new java.awt.Color(204, 255, 255));
        pword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pword1ActionPerformed(evt);
            }
        });
        getContentPane().add(pword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 210, -1));

        pword2.setBackground(new java.awt.Color(204, 255, 255));
        pword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pword2ActionPerformed(evt);
            }
        });
        getContentPane().add(pword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 210, -1));

        reg2.setBackground(new java.awt.Color(0, 51, 255));
        reg2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reg2.setForeground(new java.awt.Color(255, 255, 255));
        reg2.setText("Register");
        reg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg2ActionPerformed(evt);
            }
        });
        getContentPane().add(reg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 370, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\Project\\aaaaaa.jpg")); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg2ActionPerformed
        // TODO add your handling code here:
        
        Main connect = new Main();
        Main obj = new Main();
        
        obj.firstName = fname.getText();
        obj.lastName = lname.getText();
        obj.address = addr.getText();
        obj.email = mail.getText();
        obj.phone = phn.getText();
        
        String pass = "";
        
        if(pword1.getText().equals(pword2.getText())){
            
            pass = pword1.getText();
            
    }
        else {
        
        pword1.setText("");
        pword2.setText("");
        
        JOptionPane.showMessageDialog(null, " Passwords are Not Matching ");
        
        }
        
        if(obj.firstName.equals("") || obj.firstName.matches("@#$%^&*()_+!")){
        
            fname.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid first name");
        }
        
        else if(obj.lastName.equals("") || obj.lastName.matches("@#$%^&*()_+!")){
            
            lname.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid lirst name");
                    
        }
        
        else if(obj.address.equals("")){
            
            addr.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a address");
                           
       }
        
        else {
            
            try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c1=DriverManager.getConnection(connect.url, connect.user, connect.pss);
        
            String mysql = "INSERT INTO USER(First_Name,Last_Name,Email,Phone,Address,Password) VALUES(?,?,?,?,?,?)";
            PreparedStatement st = c1.prepareStatement(mysql);
            
            st.setString(1, obj.firstName);
            st.setString(2, obj.lastName);
            st.setString(3, obj.email);
            st.setString(4, obj.phone);
            st.setString(5, obj.address);
            st.setString(6, pass);
            
            st.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "You are Registered Succesfully , Now please log in");
            
                      
        }
        
        catch(Exception e){
            
             System.out.println(e);
        }
               
        }
        
        
        
        
    }//GEN-LAST:event_reg2ActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void addrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrActionPerformed

    private void phnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnActionPerformed

    private void pword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pword1ActionPerformed

    private void pword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pword2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registerpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField phn;
    private javax.swing.JPasswordField pword1;
    private javax.swing.JPasswordField pword2;
    private javax.swing.JButton reg2;
    // End of variables declaration//GEN-END:variables
}
