/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sportsphere2;

import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author HP
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ticket ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 70, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show Ticket Time table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 370, 40));

        tid.setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 260, 30));

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Book Now");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 350, 60));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\Project\\aaaaaa.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
              
       Main connec = new Main();


        JFrame newFrame = new JFrame("New Window");
        newFrame.setSize(500, 500);
        newFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        newFrame.setLocationRelativeTo(null);

         String[] list1=new String[100];
         String[] list2=new String[100];
         String[] list3=new String[100];
         String[] list4=new String[100];
         String[] list5=new String[100];
         String[] list6=new String[100];
         String[] list7=new String[100];
         String[] list8=new String[100];
         String[] list9=new String[100];
         String[] list10=new String[100];

        int i=2;
        list1[0]="Ticket ID";
        list2[0]="Game ID";
        list3[0]="Price ";
        list4[0]="Seat";
        list5[0]="Date";
        list6[0]="Availability";
        
        list1[1]="_________________";
        list2[1]="_________________";
        list3[1]="_________________";
        list4[1]="_________________";
        list5[1]="_________________";
        list6[1]="_________________";
        
       
        
        try{
        
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c1=DriverManager.getConnection(connec.url, connec.user, connec.pss);
            Statement s1=c1.createStatement();
            ResultSet r1=s1.executeQuery("SELECT * FROM TicketBooking");
            
            
            //String id;
            while(r1.next()){
            
                list1[i]=r1.getString(1);
                list2[i]=r1.getString(2);
                list3[i]=r1.getString(3);
                list4[i]=r1.getString(4);
                list5[i]=r1.getString(5);
                list6[i]=r1.getString(6);
               
                
             //System.out.println(list1[i]+"     "+list1[i]);
                
                       
                i=i+1;
            
            };
            c1.close();
        }
        catch(Exception e){
        
            System.out.println(e);
            
        }
        
       
        JList<String> itemList1 = new JList<>(list1);
        JList<String> itemList2 = new JList<>(list2);
        JList<String> itemList3 = new JList<>(list3);
        JList<String> itemList4 = new JList<>(list4);
        JList<String> itemList5 = new JList<>(list5);
        JList<String> itemList6 = new JList<>(list6);
       
        
        
        JPanel panel = new JPanel();
       panel.setLayout(new GridLayout(1, 5, 2, 10));
       
        panel.add(new JScrollPane(itemList1));
        panel.add(new JScrollPane(itemList2));
        panel.add(new JScrollPane(itemList3));
        panel.add(new JScrollPane(itemList4));
        panel.add(new JScrollPane(itemList5));
        panel.add(new JScrollPane(itemList6));
              
        
        JScrollPane scrollPane = new JScrollPane(panel);
        newFrame.add(scrollPane);
        newFrame.setVisible(true);
    
      
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String ticketid = tid.getText();
                 
        if(ticketid.equals("") || ticketid.matches("@#$%^&*()_+!")){
        
            tid.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid Ticket ID");
        } 
        else {
        
            Main connec = new Main();
            
            try{
            
                
    //        String sql="";
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c1=DriverManager.getConnection(connec.url, connec.user, connec.pss);
        
             String mysql = "UPDATE TicketBooking SET availability = ? WHERE ticket_id = ?";
            
             PreparedStatement st = c1.prepareStatement(mysql);
            
            st.setString(1, "Unavailable");
            st.setString(2, tid.getText());
            
            st.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "You Booked the Ticket Succesfully ");
            
                      
        }
        
        catch(Exception e){
            
    
           System.out.println(e);
           
        }
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Mainpage p1 = new Mainpage();
        p1.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tid;
    // End of variables declaration//GEN-END:variables
}
